
###Crear Usuario con rol base 
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
  "username": "maikoll8",
  "password": "123456",
  "rol": "usuario_base"
}


### Crear Usuario con rol tecnico 
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
  "username": "Pepe5",
  "password": "123456",
  "rol": "tecnico"
}

 
### Inicio de sesion(cualquier rol)
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "username": "Pepe5",
  "password": "123456"
}


###Crear Ticket usuario base
POST http://127.0.0.1:8000/api/tickets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2MTk5MjM2LCJpYXQiOjE3NzYxOTIwMzYsImp0aSI6IjM5ZGFiZGM0MmE1NDQ0NjViNTBmZTBkMjI4MGJjNzFhIiwidXNlcl9pZCI6IjcifQ.XzffGZx0YwO1uzciXU2SvrIc7m7bmWXQo138rCAAHR4
Content-Type: application/json

{
  "titulo": "Monitor roto",
  "descripcion": "El monitor tiene la pantalla quebrada ",
  "numero_equipo": "PC-15"
}

### Listar tickets usuario_base(Solo debe ver los suyos)
GET http://127.0.0.1:8000/api/tickets/list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2MTk5MzM4LCJpYXQiOjE3NzYxOTIxMzgsImp0aSI6IjkwYjE2NjlmOTIxMTQwODY5NjIxMjRmYTk0ZWFkMzYwIiwidXNlcl9pZCI6IjgifQ.sV8iEiAwVDZy73Te0mhOT-7_zCFgWOorNH_UkCzam1E

###Listar tickets tecnico(Debe poder ver todos)
GET http://127.0.0.1:8000/api/tickets/list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2MTk4MzYxLCJpYXQiOjE3NzYxOTExNjEsImp0aSI6IjdmMGY5MWMxMzk3NjRmNTJiMDBlMzFjYjA3NzRmNTBhIiwidXNlcl9pZCI6IjYifQ.dBdXXxjkMxkpHJCLDduuhoMklb--peO-zlv8eNBvY9k

### Usuario intenta cambiar el estado (Debe fallar porque su rol no se lo permite )
PUT http://127.0.0.1:8000/api/tickets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2MTk5MjM2LCJpYXQiOjE3NzYxOTIwMzYsImp0aSI6IjM5ZGFiZGM0MmE1NDQ0NjViNTBmZTBkMjI4MGJjNzFhIiwidXNlcl9pZCI6IjcifQ.XzffGZx0YwO1uzciXU2SvrIc7m7bmWXQo138rCAAHR4

{
  "estado": "resuelto"
}


### Tecnico actualiza el estado(Debe funcionar ya que es el rol correcto
PUT http://127.0.0.1:8000/api/tickets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2MTk5MzM4LCJpYXQiOjE3NzYxOTIxMzgsImp0aSI6IjkwYjE2NjlmOTIxMTQwODY5NjIxMjRmYTk0ZWFkMzYwIiwidXNlcl9pZCI6IjgifQ.sV8iEiAwVDZy73Te0mhOT-7_zCFgWOorNH_UkCzam1E
Content-Type: application/json

{
  "estado": "resuelto"
}

### Ver estadisticas 
GET  http://127.0.0.1:8000/api/tickets/estadisticas/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2MTk5MzM4LCJpYXQiOjE3NzYxOTIxMzgsImp0aSI6IjkwYjE2NjlmOTIxMTQwODY5NjIxMjRmYTk0ZWFkMzYwIiwidXNlcl9pZCI6IjgifQ.sV8iEiAwVDZy73Te0mhOT-7_zCFgWOorNH_UkCzam1E
